import Head from 'next/head';
import { GraphQLClient } from 'graphql-request';
import Hero from '../../components/pages/events-page/Hero';
import EventsList from '../../components/pages/events-page/Events';

const Events = ({ events }) => {
  return (
    <>
      <Head>
        <title>Upwards</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='relative z-10'>
        <Hero />

        <EventsList events={events} />
      </main>
    </>
  );
};

export default Events;

export async function getStaticProps() {
  const hygraph = new GraphQLClient(
    'https://api-us-east-1.hygraph.com/v2/cl8a9qn1d05a901t8fydhgwt9/master'
  );

  const { events } = await hygraph.request(
    `
        {
          events(orderBy: date_DESC) {
            id
            title
            date
            image {
              url
              width
              height
            }
            privateLink
            showPrivateLink
            description
            logos {
              id
              companyName
              logo {
                url
                width
                height
              }
            }
          }
        }
      `
  );

  return {
    props: {
      events,
    },
  };
}
