import Head from 'next/head';
import Hero from '../components/pages/home-page/Hero';

import { GraphQLClient } from 'graphql-request';
import Header from '../components/shared/Header';
import About from '../components/pages/home-page/About';
import Logos from '../components/pages/home-page/Logos';
import Events from '../components/pages/home-page/Events';

export default function Home({ companies, events }) {
  return (
    <>
      <Head>
        <title>Upwards</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <main className='relative z-10'>
        <Hero />
        <About />
        <Logos companies={companies} />
        <Events events={events} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const hygraph = new GraphQLClient(
    'https://api-eu-central-1.hygraph.com/v2/cl847c7x41mu801ug37k21fon/master'
  );

  const { companies } = await hygraph.request(
    `
      {
        companies {
          id
          companyName
          logo {
            url
            width
            height
          }
        }
      }
    `
  );

  const { events } = await hygraph.request(
    `
      {
        events {
          id
          title
          dateFreeText
          startDate
          description
          banner {
            height
            url
            width
          }
          companies {
            id
            logo {
              url
              width
              height
            }
          }
        }
      }
    `
  );

  return {
    props: {
      companies,
      events,
    },
  };
}
