import Head from 'next/head';
import Hero from '../components/pages/home-page/Hero';

import { GraphQLClient } from 'graphql-request';
import Header from '../components/shared/Header';
import About from '../components/pages/home-page/About';
import Logos from '../components/pages/home-page/Logos';
import Events from '../components/pages/home-page/Events';
import CTA from '../components/shared/CTA';

export default function Home({ logos, events }) {
  return (
    <>
      <Head>
        <title>Upwards</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='relative z-10'>
        <Hero />
        <About />
        <Logos logos={logos} />
        <Events events={events} />
        <CTA />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const hygraph = new GraphQLClient(
    'https://api-us-east-1.hygraph.com/v2/cl8a9qn1d05a901t8fydhgwt9/master'
  );

  const { logos } = await hygraph.request(
    `
      {
        logos {
          id
          companyName
          logo {
            url
            width
            height
          }
        }
      }
    `
  );

  const { events } = await hygraph.request(
    `
      {
        events(first: 3, orderBy: date_DESC) {
          id
          title
          date
          image {
            url
            width
            height
          }
          privateLink
          showPrivateLink
          description
          logos {
            id
            companyName
            logo {
              url
              width
              height
            }
          }
        }
      }
    `
  );

  return {
    props: {
      logos,
      events,
    },
  };
}
